print("اسم الطالب الأول :عبير")
Print("التخصص :علوم حاسوب ")
Print("تخرج في قبل عدة اعوام")
Print("_______" )
print("اسم الطالب الثاني:أميير")
Print("التخصص:هندسة برمجيات")
Print("العام الدراسي:المستوى الرابع")
Print("______")
Print("إسم الطالب الثالث:فجر")
Print("التخصص: تقنية معلومات ")
Print("العام الدراسي: المستوى الثالث") 
_Studentname= "abeer"
Student_age= 18
Student_gpa= 3.9
is_enrolled= True
Print(_Studentname)
Print(student_age)
Print(is_enrolled) 
